### ISSUE TITLE
Using traduora? Let us know!

### ISSUE THREAD

**Issue by anthonynsimon** [traduora/traduora#100]
As we work towards a 1.0 version, it would be great to collect a list of adopters to help us spread the word.

Feel free to mention your company or project as a comment and I'll add you to the adopters list, or you could also submit a PR to the readme :)

https://github.com/traduora/traduora#adopters

**Comment by OfficialCRUGG** [comment]
Is nobody using Traduora or why is this so empty?
Anyways, we @ taiga (taigabot.net) have been using Traduora for multiple Months and love it. The only two features we miss are Variable Support and Contexts.
We're kinda a mix between Company and Project. We're not (yet) a registered Business and are not (yet) earning any money but are a relatively large team of Volunteers using our free time to develop a super amazing Discord Bot.

**Comment by sencagri** [comment]
I just started using traduora but it have some problems when importing files about 1.5Mb. And I divided the file into smaller ones. It is still taking too much time to import xliff files. The project I am trying to import is NopCommerce language files. 

Cheers.

**Comment by vtolstov** [comment]
i'm try to use traduora instead of zanata for unistack.org site and angular spa application

**Comment by azlux** [comment]
I've start to use it for the project https://github.com/azlux/botamusique
I've setup my instance and everything good for now. (2 issue open, but it's minor)

**Comment by arelstone** [comment]
We at Ordrestyring is using this in the mobile-team. We, and our PO, is so happy with this project that our web-team will adopt  traduora too.

Using [traduora-cli](https://arelstone.github.io/traduora-cli/) makes it a breeze to easily add terms, translations, etc (sorry for advertising a package that i made)

**Comment by martijnmichel** [comment]
I am testing out Traduora but am missing some functionality in this version which makes it hard to use it for a production project. Like a review/approval system for instance.. will something like that be implemented?

**Comment by evereq** [comment]
@martijnmichel thank you for the feedback, do you mean review/approval flow when some users approve changes done by other users? Can you list other missing features which prevent you to use Traduora for your projects? That will help us a lot to decide on a future roadmap. Thank you in advance!

**Comment by martijnmichel** [comment]
I did yes. Not sure what the other things were, if there were any.

**Comment by karthic-kailanware** [comment]
I am new to tis transaltion integration into application software. can i know how should we use the this for dropdown fields

**Comment by Lerg** [comment]
I want to try using Traduora but I can't start the docker image, I get an error about MySQL driver.

```
[Nest] 1  - 04/07/2023, 2:01:12 PM     LOG [NestFactory] Starting Nest application...
2023-04-07 16:01:13 No email transport configured. Please check the documentation on how to configure the mail service at: https://docs.traduora.co/docs/configuration
2023-04-07 16:01:13 [Nest] 1  - 04/07/2023, 2:01:13 PM     LOG [InstanceLoader] PassportModule dependencies initialized +493ms
2023-04-07 16:01:13 [Nest] 1  - 04/07/2023, 2:01:13 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
2023-04-07 16:01:13 [Nest] 1  - 04/07/2023, 2:01:13 PM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
2023-04-07 16:01:13 [Nest] 1  - 04/07/2023, 2:01:13 PM     LOG [InstanceLoader] HttpModule dependencies initialized +2ms
2023-04-07 16:01:13 [Nest] 1  - 04/07/2023, 2:01:13 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2023-04-07 16:01:13 Error: connect ECONNREFUSED 127.0.0.1:3306
2023-04-07 16:01:13     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
2023-04-07 16:01:13     --------------------
2023-04-07 16:01:13     at Protocol._enqueue (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2023-04-07 16:01:13     at Protocol.handshake (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:51:23)
2023-04-07 16:01:13     at PoolConnection.connect (/opt/traduora/node_modules/mysql/lib/Connection.js:116:18)
2023-04-07 16:01:13     at Pool.getConnection (/opt/traduora/node_modules/mysql/lib/Pool.js:48:16)
2023-04-07 16:01:13     at /opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:841:18
2023-04-07 16:01:13     at new Promise (<anonymous>)
2023-04-07 16:01:13     at MysqlDriver.createPool (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:838:16)
2023-04-07 16:01:13     at MysqlDriver.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlDriver.js:284:51)
2023-04-07 16:01:13     at step (/opt/traduora/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
2023-04-07 16:01:13     at Object.next (/opt/traduora/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
2023-04-07 16:01:16 [Nest] 1  - 04/07/2023, 2:01:16 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
```

Is the docker image misconfigured?

**Comment by evereq** [comment]
Hi @Lerg , please create a separate issue for that if you need support and show what command you try to run etc. Most probably you try to run Traduora itself using Docker, but MySQL DB should be run separately as it's NOT included in the same Dockerfile. Take a look into our Docker compose files https://github.com/ever-co/ever-traduora/blob/develop/docker-compose.demo.yaml, this is a way to run both Traduora (API/UI) and MySQL DB together. Alternative will be to run Traduora in one docker VM and run MySQL on your local PC (setup it manually or again using separate docker VM).

**Comment by Lerg** [comment]
@evereq thanks, submitted a feature request.

**Comment by evereq** [comment]
> We at Binogi are trying to use Traduora and so far is looking great! One feature we're missing is the ability to filter terms by labels. Is that on your roadmap ?

Will it be possible for you do create a GitHub issue for that feature and we will try to implement as first priority? Thanks in advance!

**Comment by HugoCortell** [comment]
The Vintage Story Modding Cooperative is making use of Traduora.
We're hosting the platform free of charge to all members of the cooperative to help empower game modders.

Traduora is very lightweight, so it is the natural pick for us who can't afford better hardware. Traduora's per project ownership is also perfect for such community-focused projects, as the admin of one translation project has no ability to mess with another team's translation project. My only complaints are the installation process when not using docker being [a little difficult](https://github.com/ever-co/ever-traduora/issues/521), and the lack of [precise control over account creation](https://github.com/ever-co/ever-traduora/issues/524), and the inability to [disable project creation from users](https://github.com/ever-co/ever-traduora/issues/525).

All in all, I'm glad I picked Traduora, it's perfect for community efforts.
