### ISSUE TITLE
[export JSON error]when there is a terms for "test.a.b"

### ISSUE THREAD

**Issue by LincWong** [traduora/traduora#119]
```
TypeError: Cannot create property 'a' on string ''
    at Object.<anonymous> (/opt/traduora/src/formatters/jsonnested.js:58:42)
    at Generator.next (<anonymous>)
    at /opt/traduora/src/formatters/jsonnested.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/traduora/src/formatters/jsonnested.js:3:12)
    at Object.exports.jsonNestedExporter (/opt/traduora/src/formatters/jsonnested.js:42:40)
    at ExportsController.<anonymous> (/opt/traduora/src/controllers/exports.controller.js:96:47)
    at Generator.next (<anonymous>)
    at /opt/traduora/src/controllers/exports.controller.js:19:71
    at new Promise (<anonymous>)
GET /api/v1/projects/e3f7c90d-953e-4d72-9c70-f3b1cff6f3ec/exports?locale=de_AT&format=jsonnested HTTP/1.1 500 83 - 40.374 ms
```

export type: JSON 

switch to JSON flat will be fine

I forgot which term caused the export exception.  sorry...

**Comment by anthonynsimon** [comment]
Could you please add an example to reproduce this issue?

**Comment by clemherreman** [comment]
@LincWong This was the error I met, and it should be fixed by https://github.com/traduora/traduora/pull/116
