### ISSUE TITLE
Run compose catch error "duplicate column name"

### ISSUE THREAD

**Issue by mnikn** [traduora/traduora#60]
**Describe the bug**
run `docker-compose up`, and catch error:

```bash
traduora_1  | (node:1) UnhandledPromiseRejectionWarning: QueryFailedError: ER_DUP_FIELDNAME: Duplicate column name 'tosAndPrivacyAcceptedDate'                     
traduora_1  |     at new QueryFailedError (/opt/traduora/node_modules/typeorm/error/QueryFailedError.js:11:28)                                                    traduora_1  |     at Query.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:169:45)                                                traduora_1  |     at Query.<anonymous> (/opt/traduora/node_modules/mysql/lib/Connection.js:525:10)                                                                 traduora_1  |     at Query._callback (/opt/traduora/node_modules/mysql/lib/Connection.js:491:16)                                                                   traduora_1  |     at Query.Sequence.end (/opt/traduora/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)                                                traduora_1  |     at Query.ErrorPacket (/opt/traduora/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)                                                     traduora_1  |     at Protocol._parsePacket (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:291:23)                                                      traduora_1  |     at Parser._parsePacket (/opt/traduora/node_modules/mysql/lib/protocol/Parser.js:433:10)                                                          traduora_1  |     at Parser.write (/opt/traduora/node_modules/mysql/lib/protocol/Parser.js:43:10)                                                                  traduora_1  |     at Protocol.write (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:38:16)                                                              traduora_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                    traduora_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**To Reproduce**
run `docker-compose up`.

**Environment**
 - OS: Windows 10
 - Version 0.12.0

**Comment by anthonynsimon** [comment]
Hey, I wasn't able to reproduce the error on a fresh install.

Is this the first time you start traduora using docker-compose in that machine? It seems like it could be an issue with the migrations.

**Comment by mnikn** [comment]
@anthonynsimon Sorry, It work after I try to delete docker container and restart it, so this issue should be closed
